### PR TITLE
thread safe rpcclient

### PR DESCRIPTION
**Pull request by Asuan**
Move global var to local to reduce chance for wrong response.
It still not fully thread safe.
But get wrong response by correct request (in case multiple RPC request) looks not good.

### CODE REVIEW

**Comment by denkhaus** [comment]
@Asuan Why did you close this issue. I think in the long we need to address this and go with a completely new thread save wallet RPC client. Do you have any suggestions.? Maybe the golang native one?

**Comment by Asuan** [comment]
The PR was conflicted with lastest changes.
Yes I'm native with golang, and RPC client need to be rewrited a little.
a. remove double marshal unmarshal.
b. remove instance golbal var (example in the code)
c. tune http client
I'll create PR with RPC client update. But I do not have time for now.

**Comment by denkhaus** [comment]
The RPC-Client has to be fully async, like the golang native one (https://golang.org/src/net/rpc/client.go). Otherwise you have to secure the CallAPI method by a mutex and use it synchronized.

**Comment by Asuan** [comment]
mutex totally bad idea to sync api calls.
we have racing with 
````
req         rpcRequest
res         rpcResponseString
````
also ffjson.Encoder and ffjson.Decoder is not thread-safe (`This should not be used by more than one goroutine at the time.`).

**Comment by denkhaus** [comment]
Already clear. But if you protect CallAPI with a mutex right from the beginning, you only allow one access at the time. But that's not the way I would go.

**Pull request closed without merging**
