### PR TITLE
Fix Assert unmarshal problem

### PR DESCRIPTION
**Pull request by Asuan**
We have different types of the Extensions in JSON view:
`[]` or `{}` But we do not use it
so comment for now.

### CODE REVIEW

**Comment by Asuan** [comment]
@denkhaus

**Comment by denkhaus** [comment]
Hi @Asuan  I changed extensions code a few days ago. Look at dev branch and tell me if that works for you. Simply commenting this out may not be perfect in regard to operation marshalling. I will investigate further.

**Comment by Asuan** [comment]
Your fix also solve problem.
But so many codes updated.

**Comment by gitmonster** [comment]
Since extensions is used in almost every entity all ffjson files have to be updated too. So yes...

**Pull request closed without merging**
