### PR TITLE
Fixes #16 : Fixing error on decrypt by allowing to check if the decry…

### LINKED ISSUE #16: Memo Decrypt function does not work on receiver decryption, but only for sender
# How to Reproduce
Call Memo.Decrypt using the private key of the receiver of the memo transfer

# Expected Behaviour
Should decrypt successfully if the shared secret between the parties is correct

# What happens
Breaks, sometimes with a panic on `pad` function, sometimes throws error on checksum
On sender the Decrypt works

### PR DESCRIPTION
**Pull request by saniales**
…pter is one of the parties.

### CODE REVIEW

**Comment by denkhaus** [comment]
Hi @saniales i close this pull request according to issue #15 . Decrypt was meant to be called from the receiver site. This builds the shared secret by the receiver's priv key and the sender's public key. In rare cases, when you build the "memo" by your own, you have to initialize the params from senders perspective.

**Comment by Asuan** [comment]
@denkhaus  
Sender and Reviver should have way to decrypt Memo from transaction data without additional manipulating.
Before we have way to decrypt memo from Sender side after we have way to decrypt from Receiver side.
But both side should have way to decrypt...
so fix is looking right.

**Comment by saniales** [comment]
Thx

**Comment by denkhaus** [comment]
@Asuan Feel free to reopen this issue if you have any doubts.

**Comment by Asuan** [comment]
There are an example bellow [copy of memo](https://github.com/denkhaus/bitshares/blob/master/examples/memo/main.go) example ).
The with current PR all works fine.
Without It will fail.
BTW fail of decoding Memo should not crash Unmarshal (It is okay to fail decrypt 3d party memos)
````
package main

import (
	"fmt"
	"log"
	"math/rand"

	"github.com/denkhaus/bitshares/config"
	"github.com/denkhaus/bitshares/types"
	"github.com/juju/errors"
)

const (
	memoSrc       = "My secret memo works!"
	pubKeyAString = "BTS5zzvbDtkbUVU1gFFsKqCE55U7JbjTp6mTh1usFv7KGgXL7HDQk"
	privKeyAWif   = "5Hx8KiHLnc3pDLkwe2jujkTTJev72n3Qx7xtyaRNBsJDuejzh9u"
	pubKeyBString = "BTS5Z3vsgH6xj6HLXcsU38yo4TyoZs9AUzpfbaXbuxsAYPbutWvEP"
	privKeyBWif   = "5KRZv3ZmkcE71K9KwEKG6pV6pyufkMQgCJrCu8xKLf2y7R7J8YK"
)

func main() {
	config.SetCurrentConfig(config.ChainIDBTS)

	pubKeyA, err := types.NewPublicKeyFromString(pubKeyAString)
	if err != nil {
		log.Fatal(errors.Annotate(err, "NewPublicKeyFromString [key A]"))
	}

	pubKeyB, err := types.NewPublicKeyFromString(pubKeyBString)
	if err != nil {
		log.Fatal(errors.Annotate(err, "NewPublicKeyFromString [key B]"))
	}

	memo := types.Memo{
		From:  *pubKeyA,
		To:    *pubKeyB,
		Nonce: types.UInt64(rand.Int63()),
	}

	privKeyA, err := types.NewPrivateKeyFromWif(privKeyAWif)
	if err != nil {
		log.Fatal(errors.Annotate(err, "NewPrivateKeyFromWif [key A]"))
	}

	if err := memo.Encrypt(privKeyA, memoSrc); err != nil {
		log.Fatal(errors.Annotate(err, "Encrypt"))
	}

	privKeyB, err := types.NewPrivateKeyFromWif(privKeyBWif)
	if err != nil {
		log.Fatal(errors.Annotate(err, "NewPrivateKeyFromWif [key B]"))
	}

	memoDst, err := memo.Decrypt(privKeyB)
	if err != nil {
		log.Fatal(errors.Annotate(err, "Encrypt"))
	}

	if memoSrc != memoDst {
		log.Fatalf("decryption error: memo is %q", memoDst)
	}

	fmt.Printf("decrypted memo for B side is %q\n", memoDst)
        // Try to decryt from sender side
	memoDst, err = memo.Decrypt(privKeyA)
	if err != nil {
		log.Fatal(errors.Annotate(err, "Encrypt"))
	}
	if memoSrc != memoDst {
		log.Fatalf("decryption error: memo is %q", memoDst)
	}
	fmt.Printf("decrypted memo for A side is %q\n", memoDst)
}

````

**Comment by Asuan** [comment]
@denkhaus   I propose to merge current PR. It will provide simple way for decrypt memos for sender and receiver.

**Comment by saniales** [comment]
Merging this will provide easiness to decrypt from new sides without losing of compatibility

**Comment by denkhaus** [comment]
Ok i check.

**Pull request merged**
